// Re-export everything from slices for backward compatibility
// This file is kept for backward compatibility - use imports from ./slices directly

export {
  // Auth
  login,
  logout,
  updateTokens,
  updateUser,
  selectAuth,
  selectUser,
  selectToken,
  selectAccessToken,
  selectRefreshToken,
  selectIsAuthenticated,
  // UI
  setNavigation,
  setStudentSidebarOpen,
  setAdminSidebarOpen,
  setGlobalLoading,
  addNotification,
  removeNotification,
  clearNotifications,
  selectUI,
  selectCurrentNavigation,
  selectStudentSidebarOpen,
  selectAdminSidebarOpen,
  selectGlobalLoading,
  selectNotifications,
  // Student
  fetchDashboard,
  fetchProfile,
  fetchMyCourses,
  fetchCourseDetails,
  fetchCourseModules,
  fetchQuizzesByCourse,
  fetchCourseQuizzes,
  fetchAssignmentsByCourse,
  fetchCourseAssignments,
  fetchCertificates,
  fetchLeaderboard,
  fetchReferralInfo,
  fetchSupportQueries,
  clearStudentData,
  updateProfileLocal,
  invalidateDashboard,
  invalidateProfile,
  invalidateCourses,
  invalidateCertificates,
  selectDashboard,
  selectDashboardData,
  selectDashboardLoading,
  selectProfile,
  selectProfileData,
  selectProfileLoading,
  selectCourses,
  selectCoursesList,
  selectCoursesLoading,
  selectCourseDetails,
  selectCourseModules,
  selectQuizzes,
  selectQuizzesByCourse,
  selectCourseQuizzes,
  selectAssignments,
  selectAssignmentsByCourse,
  selectCourseAssignments,
  selectCertificates,
  selectCertificatesList,
  selectLeaderboard,
  selectReferral,
  selectReferralData,
  selectSupport,
  selectSupportQueries,
} from './slices';
